# Generated by Django 5.2.16 on 2026-08-01 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('alias', models.CharField(blank=True, max_length=20, null=True)),
                ('alias_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_number', models.CharField(max_length=20)),
                ('device_name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.controlpoint')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_date', models.CharField(max_length=20)),
                ('connection_time', models.FloatField(blank=True, null=True)),
                ('date_time', models.FloatField()),
                ('result_line', models.IntegerField(default=1)),
                ('info_line', models.IntegerField(default=1)),
                ('connected', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('tag', models.IntegerField()),
                ('timer_code', models.IntegerField()),
                ('event_code', models.IntegerField()),
                ('time', models.FloatField()),
                ('reader_id', models.CharField(max_length=20)),
                ('antenna', models.CharField(max_length=20)),
                ('read_power', models.CharField(max_length=20)),
                ('reader_sequence', models.CharField(max_length=20)),
                ('read_type', models.CharField(max_length=1)),
                ('device_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.devicesession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
                ('device_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.devicesession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GunStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gun_starts', to='app.device')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='InfoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_device_id', models.CharField(max_length=20)),
                ('line', models.IntegerField()),
                ('info_type', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('info', models.CharField(max_length=20)),
                ('device_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.devicesession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('shift_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.gunstart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='controlpoint',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_points', to='app.race'),
        ),
        migrations.AddConstraint(
            model_name='devicesession',
            constraint=models.UniqueConstraint(fields=('device', 'date_time'), name='unique_device_datetime'),
        ),
    ]
