# Generated by Django 5.2.16 on 2026-08-02 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gunstart',
            name='device',
        ),
        migrations.AddField(
            model_name='gunstart',
            name='device_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.devicesession'),
            preserve_default=False,
        ),
    ]
