# Generated by Django 5.2.16 on 2026-08-02 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_gunstart_device_gunstart_device_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunstart',
            name='device_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.devicesession'),
        ),
    ]
