# Generated by Django 5.2.16 on 2026-08-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_gunstart_device_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesession',
            name='date_time',
            field=models.CharField(max_length=8),
        ),
    ]
